### PR TITLE
Added AllStrings param to excel plugin

### PR DESCRIPTION
**Pull request by NDMO**
Added the all strings param to the excel plugin, very generic way to solve #97 .  
Allows all the rows to be returned as strings.    
Note: Also looks like this included changes from other pull request.

### CODE REVIEW

**Comment by aellis** [comment]
@NMDO I would like to change the naming of this model argument to be a little more descriptive.  Lets make it 'ReturnAllDataAsStrings'.

**Comment by OnlyAGhost** [comment]
@NDMO I am seeing a conflict on this?

**Comment by OnlyAGhost** [comment]
@NDMO when you get a chance can you review the conflict on this PR?

**Comment by NDMO** [comment]
@OnlyAGhost Should be good to go.

**Pull request merged**
